In [1]:
import numpy as np


# numpy数组的合并 `vstack` `hstack` `dstack`
- vs 纵向
- hs 水平方向
- ds 深度拆分
## 数组的拆分 `vsplit` `hsplit` `dsplit`

In [4]:
m = np.arange(6)
m = np.array([m]*6)
m

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [12]:
x = range(6)
n = np.array([x]*6)
n

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [21]:
#ret = np.dstack(n,axis = 1)
ret  = np.concatenate([m,n],axis=1)
ret

array([[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]])

In [27]:
list = np.split(ret,[6],axis=1)
list

[array([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]]),
 array([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]])]